name: Update README Questions Table
"on":
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  update_readme:
    runs-on: ubuntu-latest
    name: Update README
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn readme
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Update README table"