name: Update README Questions Table
"on":
  workflow_dispatch:
jobs:
  update_readme:
    runs-on: ubuntu-latest
    name: Update README
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn readme
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: Ammar Ahmed
          author_email: ammar.ahmed2203@gmail.com
          default_author: github_actions
          message: "Update README table"